SELECT * FROM BASICENTITY_TW;
SELECT * FROM MEMBER_ENTITY_TW;
SELECT * FROM DEPARTMENT_TW;
SELECT * FROM EMPLOYEE_TW;

SELECT * FROM STUDENT_TW1;
SELECT * FROM LESSON_TW1;

SELECT * FROM STUDENT_TW;
SELECT * FROM LECTURE_TW;

-- 1. 테이블과 시퀀스를 완전히 삭제 (순서 중요)
DROP TABLE STUDENT_TW CASCADE CONSTRAINTS;
DROP TABLE LECTURE_TW CASCADE CONSTRAINTS;
DROP SEQUENCE sd_sdno;
DROP SEQUENCE sd_ltno;

-- 2. 확정
COMMIT;